### ISSUE TITLE
Dependencies and installation process

### ISSUE THREAD

**Issue by leugenea** [papyros/papyros-shell#11]
I suppose that people who familiar with Qt/Wayland/etc. and their packages can easily install all needed dependencies and run shell. But others can't.
We can write some short (I think it'll be short) manual about installation process: what packages user must install (we can focus on Arch Linux or/and Ubuntu (some version) only) and what to run to make project (and all projects which it depends on).
Also for Arch Linux we can write PKGBUILD and push this project to AUR.

**Comment by iBeliever** [comment]
@atsjj I found a working solution, check out my solution on #20 and see if that works for you as well.

**Comment by atsjj** [comment]
@iBeliever I will recompile this evening and let you know what happens.

**Comment by atsjj** [comment]
@iBeliever I did a recompile, but at this point I'm seeing some funky stuff with QT5 and I think it might be driver related, i.e. KMS and proprietary NVIDIA driver.

When Nouveau is updated with better support for GM204/GTX970/980, I will give it another pass.

**Comment by iBelieve** [comment]
Closing now as we have an updated README and instructions for testing at http://papyros.io/download.
