### ISSUE TITLE
App shelf still transparent when windows are maximized

### ISSUE THREAD

**Issue by ctnlaring** [papyros/papyros-shell#110]
I'm not sure if the transparency just ins't finished but it's still transparent when I maximize windows.

**Comment by iBelieve** [comment]
@Collinthegeek Can you please include more details, such as what app you used and how you maximized it (via a maximize button or by double-clicking the title bar), as well as the version of the `papyros-shell` package. Thanks!

**Comment by ctnlaring** [comment]
Every app I tried. specifically epiphany/gnome-web. I double clicked the
title bar.

**Comment by IdrissDimson** [comment]
@Collinthegeek maybe a screenshot would help?

**Comment by iBelieve** [comment]
@Collinthegeek Is this still an issue? Can you make sure you're running the latest packages from the Arch repo or from the latest Git? It should be working correctly now.

**Comment by iBelieve** [comment]
I just checked and the panel properly goes dark when a window is maximized.
