### ISSUE TITLE
(process:7269): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.background' does not contain a key named 'show-desktopicons' Trace/breakpoint trap (core dumped)

### ISSUE THREAD

**Issue by betseg** [papyros/papyros-shell#111]
I type "greenisland --fake-screen ~/.config/fake-screen.json --shell io.papyros.shell" but screen crashes after 2 seconds whhile it says Welcome.

$ greenisland --fake-screen ~/.config/fake-screen.json --shell io.papyros.shell
QML debugging is enabled. Only use this in a safe environment.
greenisland.protocols.wlshell.trace: GreenIsland::WlShellGlobal::WlShellGlobal(QObject_)
greenisland.protocols.wlshell.trace: virtual const wl_interface_ GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.wlshell.trace: virtual const wl_interface\* GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: GreenIsland::XdgShellGlobal::XdgShellGlobal(GreenIsland::Compositor_)
greenisland.protocols.xdgshell.trace: virtual const wl_interface_ GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: virtual const wl_interface\* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.gtkshell.trace: GreenIsland::GtkShellGlobal::GtkShellGlobal(QObject_)
greenisland.protocols.gtkshell.trace: virtual const wl_interface_ GreenIsland::GtkShellGlobal::interface() const
greenisland.protocols.gtkshell.trace: virtual const wl_interface\* GreenIsland::GtkShellGlobal::interface() const
greenisland.screenbackend.fake: Load configuration from "/home/arda/.config/fake-screen.json"
greenisland.screenconfiguration: Output settings: QMap(("mode", QVariant(QVariantMap, QMap(("refreshRate", QVariant(double, 60000))("size", QVariant(QVariantMap, QMap(("height", QVariant(double, 600))("width", QVariant(double, 1024))))))))("name", QVariant(QString, "Fake1"))("orientation", QVariant(double, 2))("position", QVariant(QVariantMap, QMap(("x", QVariant(double, 0))("y", QVariant(double, 0))))))
greenisland.screenconfiguration: Output name: "Fake1"
greenisland.screenconfiguration: Output primary: false
greenisland.screenconfiguration: Output position: QPoint(0,0)
greenisland.screenconfiguration: Output size: QSize(1024, 600)
greenisland.screenconfiguration: Output refresh rate: 60000
greenisland.screenconfiguration: Output orientation: Qt::ScreenOrientation(LandscapeOrientation)
greenisland.screenbackend.fake: Output added "Fake1" QRect(0,0 1024x600)
greenisland.compositor: Added primary output "Fake1" with geometry QRect(0,0 1024x600)
greenisland.compositor: Showing window for output "Fake1" QRect(0,0 1024x600)
greenisland.compositor: Loading scene on output "Fake1" QRect(0,0 1024x600)
greenisland.compositor: Loading "io.papyros.shell" shell for output "Fake1" QRect(0,0 1024x600)
file:///usr/lib/qt/qml/Material/MainView.qml:64: ReferenceError: clientSideDecorations is not defined
greenisland.compositor: QML scene loaded successfully
greenisland.compositor: Scene load time: 195 ms
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7fff02cb6fe0), parent's thread is QThread(0x1dbdcd0), current thread is QThread(0x2522df0)
greenisland.compositor: EGL version: 1.4 (DRI2)
greenisland.compositor: EGL vendor: Mesa Project
greenisland.compositor: EGL client APIs: OpenGL OpenGL_ES OpenGL_ES2 OpenGL_ES3 
greenisland.compositor: EGL extensions: EGL_MESA_drm_image EGL_MESA_configless_context EGL_WL_bind_wayland_display
    EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_image EGL_KHR_get_all_proc_addresses
    EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_gl_renderbuffer_image EGL_KHR_surfaceless_context
    EGL_KHR_create_context EGL_NOK_swap_region EGL_NOK_texture_from_pixmap
    EGL_CHROMIUM_sync_control EGL_EXT_create_context_robustness
    EGL_EXT_image_dma_buf_import EGL_NV_post_sub_buffer 
greenisland.compositor: Surface created QWaylandQuickSurface(0x2747210)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7fff02cb6fe0), parent's thread is QThread(0x1dbdcd0), current thread is QThread(0x2522df0)
hawaii.qml.hardware: Populate initial devices list
virtual QStringList Solid::Backends::UPower::UPowerManager::allDevices()  error:  "org.freedesktop.DBus.Error.InvalidSignature"
hawaii.qml.hardware.storagedevice: Added storage device "/org/freedesktop/UDisks2/block_devices/sdb2"
hawaii.qml.hardware.storagedevice: Added storage device "/org/freedesktop/UDisks2/block_devices/sdb1"
hawaii.qml.hardware.storagedevice: Added storage device "/org/freedesktop/UDisks2/block_devices/sda2"
QQmlExpression: Expression file:///usr/share/greenisland/shells/io.papyros.shell/notifications/NotificationsView.qml:52:16 depends on non-NOTIFYable properties:
    NotificationServer::notifications

(process:7553): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.background' does not contain a key named 'show-desktopicons'
Trace/breakpoint trap (core dumped)

**Comment by iBelieve** [comment]
Papyros no longer uses GSettings, so it doesn't require any GNOME-specific GSettings schemas.
