### ISSUE TITLE
How can download?

### ISSUE THREAD

**Issue by rexpa** [papyros/papyros-shell#113]
sorry i'm new with this, how can i download this OS?, I need to do a research on it, and I do not get how to download, thanks

**Comment by iBelieve** [comment]
Directions are available on our website: http://papyros.io/download

The full OS is not available yet, but you can test the desktop environment on top of an existing Arch Linux installation.

**Comment by iBelieve** [comment]
I'm closing this as there hasn't been any further discussion. Please join the [Gitter chatroom](gitter.im/papyros/papyros) if you have any questions or problems with installing the shell. Thanks!
