### ISSUE TITLE
Cursor speed is way to fast when running as a full session [$20 awarded]

### ISSUE THREAD

**Issue by iBelieve** [papyros/papyros-shell#120]
Might be related to running on a HiDPI screen.
##

**Comment by iBelieve** [comment]
Reported upstream as https://bugreports.qt.io/browse/QTBUG-46808.

**Comment by IdrissDimson** [comment]
so is this a qt bug or a problem with the code

**Comment by iBelieve** [comment]
@VirusKA It doesn't work out-of-the-box for a sample Qt project, so it would seem to be an upstream Qt bug. However, it might not be a Qt bug, and could either be a libinput bug or just simply a misconfigured input device.

**Comment by iBelieve** [comment]
Upstream acknowledged this as a valid bug and suggested we try using libinput instead. That's definitely what we want, and I actually thought we were, but it turns out it wasn't being compiled in Qt. So now I'm working on getting the Qt libinput plugin enabled and compiled.

**Comment by IdrissDimson** [comment]
oh nice

**Comment by iBelieve** [comment]
Yep, using the libinput plugin fixed it. Cursor works great now!
