### ISSUE TITLE
Icon theme not set correctly in the session [$20 awarded]

### ISSUE THREAD

**Issue by iBelieve** [papyros/papyros-shell#121]
##

**Comment by VirusKA** [comment]
Any updates?

**Comment by alexkreidler** [comment]
@iBeliever Can you add more details?

**Comment by IdrissDimson** [comment]
That would actually be nice. I'm not 100% sure what that means.

**Comment by marosoft** [comment]
Could you add more details? Is it about user preferences? I would suggest to add the steps to reproduce and a proper behaviour.

**Comment by iBelieve** [comment]
Sorry guys, I forgot to add more details when I created the issue. Basically

**What happens**
1. Launch the shell from an existing session (GNOME, whatever)
2. Notice how all or most the apps in the panel and launcher have the correct icons
3. Now launch the shell from a login manager (GDM, SDDM, whatever)
4. Now all the apps use the default colored circle with the first letter as a placeholder because the real icons won't load

**What should happen**

I should see the real app icons when logging in as a full wayland session.
