### ISSUE TITLE
Listen to keyboard events for sound

### ISSUE THREAD

**Issue by iBelieve** [papyros/papyros-shell#134]
Volume up, down, and mute.

**Comment by ghost** [comment]
[seems to be the best way](https://wiki.archlinux.org/index.php/Acpid)

**Comment by VirusKA** [comment]
^this

**Comment by ghost** [comment]
Yes, acpid events are good, but what is about the mentioned _SLPB_ _SBTN_? Does it also concern the volumeup, volumedown,.... buttons? if so, should we ask in the installer if they press the key, listen to that and push it into the config?

**Comment by cptn-cosmo** [comment]
Imho it should also include screen brightness (or does wayland handle this? then papyros shell should still display an indicator, like os x does https://www.dropbox.com/s/kzejnc3o9qgxbcj/Screenshot%202015-07-07%2014.56.00.png?dl=0

(design should obviously be different, close to the volume indicator)

It would be nice if the same would be possible for keyboard backlight brightness... 

I am also not sure about play/pause and next / prev track... if that should be handled by the shell or the running multimedia application...

**Comment by VirusKA** [comment]
We should merge that commit^

**Comment by VirusKA** [comment]
^anyone review this yet?

**Comment by IdrissDimson** [comment]
^anyone review this yet?

**Comment by 29jm** [comment]
I tested it and it works, but there are some issues: pressing VolumeUp increases the volume by 6 and VolumeDown decreases it by 4 (a rounding issue maybe?), perhaps VolumeMute could be a toggle like in Gnome 3 (feedback needed), and also, this commit has whitespace issues (spaces on empty lines 35 and 51).

**Comment by IdrissDimson** [comment]
huh according to the code, luxrck meant the volume to go up and down by 5. the whitespacing is easy to fix.

**Comment by 29jm** [comment]
@VirusKA Yeah I've seen that, but the code itself is weird, I think it could be improved: when the slider is moved, it changes the master value, and the slider is changed to the master value (yes, it's set twice per move, the second time the binding is restored). So it could be a bug in the Sound class (C++).
Also, the `sound` object has a `muted` property that could just be toggled when VolumeMute is pressed.

**Comment by 29jm** [comment]
@VirusKA I've made a fix, it was a rounding error in [sound.cpp](https://github.com/papyros/papyros-shell/blob/develop/modules/Papyros/Desktop/mixer/sound.cpp). I'll make pull request later.

**Comment by IdrissDimson** [comment]
noice
