### ISSUE TITLE
Display volume change notifications [$20 awarded]

### ISSUE THREAD

**Issue by iBelieve** [papyros/papyros-shell#135]
##

**Comment by oneiricsky** [comment]
Any news on this one?

**Comment by VirusKA** [comment]
yeah this is the one where i seen nor heard anything

**Comment by ozwaldorf** [comment]
It shouldn't be a notification, but a toast instead. Having a notification for each change could get quite annoying.

**Comment by alexkreidler** [comment]
Should this be a feature implemented on the OS layer or kind of like an event listener for changes on the sound driver layer?

**Comment by IdrissDimson** [comment]
I agree with @The5heepDev. A toast would also be easier.

**Comment by ctnlaring** [comment]
Maybe I'm missing something but this shouldn't be very hard to implement. The percentage changes in the controls pane so you should be able to just have the same thing that controls that control a notification right?

**Comment by IdrissDimson** [comment]
awesome bounty's are back!

**Comment by iBelieve** [comment]
This depends on fixing #191 first.

**Comment by VirusKA** [comment]
now that #191's done, how do you wanna do this

**Comment by IdrissDimson** [comment]
now that #191's fixed, how do you wanna do the notifications?

**Comment by iBelieve** [comment]
I'm going to implement this by displaying volume change notifications as a normal notification popup in the button right corner, plus a progress bar.

**Comment by IdrissDimson** [comment]
that's nice
