### ISSUE TITLE
Remove Qt-git dependency on Arch

### ISSUE THREAD

**Issue by taaem** [papyros/papyros-shell#143]
Qt 5.5 is now in the stable repo so no need anymore to depend for the upstream version.
This would make it much more easier to install and test the shell especially, when you're coming from KDE or another Qt-based DE.

**Comment by ricardomv** [comment]
We still need to rebuild qt5 to enable support for opengles2 that we need to run a wayland compositor. But we are working to build on top of a stable release instead of the git repository

**Comment by ricardomv** [comment]
This is not a shell issue so i am closing this. ~~You can see the pull request that fixes this in https://github.com/papyros/repository/pull/3~~ This has been fixed in https://github.com/papyros/repository branch testing
