### ISSUE TITLE
[Question] how to run on wayland?

### ISSUE THREAD

**Issue by changsijay** [papyros/papyros-shell#145]
Hi, I am using archlinux and finished install papyros-shell.
How to run it from text mode console?

I only installed wayland and weston. no X server.
and I can run weston normally from tty1.
Thanks a lot,

**Comment by kingwill101** [comment]
To run the shell from a virtual terminal as a full Wayland compositor:

`greenisland --platform eglfs --shell io.papyros.shell`

please note the shell isnt yet in a usable state

**Comment by changsijay** [comment]
I can run it by above command now, looks pretty nice,
although it hung right after the desktop show up.
