### ISSUE TITLE
Cant run latest pull

### ISSUE THREAD

**Issue by kingwill101** [papyros/papyros-shell#146]
Just built the shell from the sources but i keep getting these errors and i cant seem to find a reference to the Desktop plugin on github

![screenshot from 2015-07-24 08-47-47](https://cloud.githubusercontent.com/assets/1114368/8875741/dc3727da-31e0-11e5-9fbe-8391e1cf8b18.png)

**Comment by ricardomv** [comment]
You need to provide more information. Looks like you are using fedora the install instructions in the readme should work. Can you provide the folders where you installed the required dependencies and papyros-shell itself ?

**Comment by kingwill101** [comment]
Material components

`/usr/lib64/qt5/qml/Material`

greenisland 
`
`/usr/bin/greenisland
/usr/bin/greenisland-launcher
/usr/bin/greenisland-screencaster
/usr/lib64/libGreenIsland.so.0
/usr/lib64/libGreenIsland.so.0.5.95
/usr/lib64/qt5/plugins/greenisland/plasma.so
/usr/lib64/qt5/qml/GreenIsland
/usr/lib64/qt5/qml/GreenIsland/ContrastEffect.qml
/usr/lib64/qt5/qml/GreenIsland/SurfaceRenderer.qml
/usr/lib64/qt5/qml/GreenIsland/libgreenislandplugin.so
/usr/lib64/qt5/qml/GreenIsland/qmldir
/usr/share/doc/greenisland
/usr/share/doc/greenisland/AUTHORS
/usr/share/doc/greenisland/LICENSE.BSD
/usr/share/doc/greenisland/LICENSE.GPL
/usr/share/doc/greenisland/LICENSE.LGPL
/usr/share/doc/greenisland/README.md
/usr/share/greenisland/screen-data
/usr/share/greenisland/screen-data/four-960x540.json
/usr/share/greenisland/screen-data/one-1024x768.json
/usr/share/greenisland/screen-data/one-1920x1080.json
/usr/share/greenisland/screen-data/phone-1080x1920.json
/usr/share/greenisland/screen-data/phone-720x1280.json
/usr/share/greenisland/screen-data/rotation-inverted.json
/usr/share/greenisland/screen-data/rotation-left.json
/usr/share/greenisland/screen-data/rotation-right.json
/usr/share/greenisland/screen-data/two-1024x768.json
/usr/share/greenisland/screen-data/two-rotated.json
/usr/share/greenisland/screen-data/two-uneven.json
/usr/share/greenisland/shells
/usr/share/greenisland/shells/org.greenisland.simple
/usr/share/greenisland/shells/org.greenisland.simple/Compositor.qml
/usr/share/greenisland/shells/org.greenisland.simple/PopupWindow.qml
/usr/share/greenisland/shells/org.greenisland.simple/PopupWindowAnimation.qml
/usr/share/greenisland/shells/org.greenisland.simple/ScreenView.qml
/usr/share/greenisland/shells/org.greenisland.simple/ScreenZoom.qml
/usr/share/greenisland/shells/org.greenisland.simple/ToplevelWindow.qml
/usr/share/greenisland/shells/org.greenisland.simple/ToplevelWindowAnimation.qml
/usr/share/greenisland/shells/org.greenisland.simple/TransientWindow.qml
/usr/share/greenisland/shells/org.greenisland.simple/TransientWindowAnimation.qml
/usr/share/greenisland/shells/org.greenisland.simple/WindowAnimation.qml
/usr/share/greenisland/shells/org.greenisland.simple/WindowManagement.js
/usr/share/greenisland/shells/org.greenisland.simple/WindowWrapper.qml
1/usr/share/greenisland/shells/org.greenisland.simple/images
/usr/share/greenisland/shells/org.greenisland.simple/images/wallpaper.png
/usr/share/greenisland/shells/org.greenisland.simple/overlays
/usr/share/greenisland/shells/org.greenisland.simple/overlays/UnresponsiveOverlay.qml
`
solid 

`/usr/bin/solid-hardware5
/usr/share/doc/kf5-solid
/usr/share/doc/kf5-solid/COPYING.LIB
/usr/share/doc/kf5-solid/README.md
/usr/share/doc/kf5-solid/TODO`

Qt 

`/etc/xdg/QtProject
/etc/xdg/qtchooser
/etc/xdg/qtchooser/5-64.conf
/etc/xdg/qtchooser/5.conf
/etc/xdg/qtchooser/default.conf
/usr/lib64/cmake
/usr/lib64/cmake/Qt5
/usr/lib64/cmake/Qt5Concurrent
/usr/lib64/cmake/Qt5Core
/usr/lib64/cmake/Qt5DBus
/usr/lib64/cmake/Qt5Gui
/usr/lib64/cmake/Qt5Network
/usr/lib64/cmake/Qt5Network/Qt5Network_QConnmanEnginePlugin.cmake
/usr/lib64/cmake/Qt5Network/Qt5Network_QGenericEnginePlugin.cmake
/usr/lib64/cmake/Qt5Network/Qt5Network_QNetworkManagerEnginePlugin.cmake
/usr/lib64/cmake/Qt5OpenGL
/usr/lib64/cmake/Qt5PrintSupport
/usr/lib64/cmake/Qt5Sql
/usr/lib64/cmake/Qt5Sql/Qt5Sql_QSQLiteDriverPlugin.cmake
/usr/lib64/cmake/Qt5Test
/usr/lib64/cmake/Qt5Widgets
/usr/lib64/cmake/Qt5Xml
/usr/lib64/libQt5Concurrent.so.5
/usr/lib64/libQt5Concurrent.so.5.5
/usr/lib64/libQt5Concurrent.so.5.5.0
/usr/lib64/libQt5Core.so.5
/usr/lib64/libQt5Core.so.5.5
/usr/lib64/libQt5Core.so.5.5.0
/usr/lib64/libQt5DBus.so.5
/usr/lib64/libQt5DBus.so.5.5
/usr/lib64/libQt5DBus.so.5.5.0
/usr/lib64/libQt5Network.so.5
/usr/lib64/libQt5Network.so.5.5
/usr/lib64/libQt5Network.so.5.5.0
/usr/lib64/libQt5Sql.so.5
/usr/lib64/libQt5Sql.so.5.5
/usr/lib64/libQt5Sql.so.5.5.0
/usr/lib64/libQt5Test.so.5
/usr/lib64/libQt5Test.so.5.5
/usr/lib64/libQt5Test.so.5.5.0
/usr/lib64/libQt5Xml.so.5
/usr/lib64/libQt5Xml.so.5.5
/usr/lib64/libQt5Xml.so.5.5.0
/usr/lib64/qt5
/usr/lib64/qt5/imports
/usr/lib64/qt5/libexec
/usr/lib64/qt5/plugins
/usr/lib64/qt5/plugins/bearer
/usr/lib64/qt5/plugins/bearer/libqconnmanbearer.so
/usr/lib64/qt5/plugins/bearer/libqgenericbearer.so
/usr/lib64/qt5/plugins/bearer/libqnmbearer.so
/usr/lib64/qt5/plugins/designer
/usr/lib64/qt5/plugins/generic
/usr/lib64/qt5/plugins/iconengines
/usr/lib64/qt5/plugins/imageformats
/usr/lib64/qt5/plugins/platforminputcontexts
/usr/lib64/qt5/plugins/platforms
/usr/lib64/qt5/plugins/platformthemes
/usr/lib64/qt5/plugins/printsupport
/usr/lib64/qt5/plugins/script
/usr/lib64/qt5/plugins/sqldrivers
/usr/lib64/qt5/plugins/sqldrivers/libqsqlite.so
/usr/lib64/qt5/plugins/styles
/usr/share/doc/qt5
/usr/share/doc/qt5-qtbase
/usr/share/doc/qt5-qtbase/LGPL_EXCEPTION.txt
/usr/share/doc/qt5-qtbase/LICENSE.FDL
/usr/share/doc/qt5-qtbase/LICENSE.LGPLv21
/usr/share/doc/qt5-qtbase/LICENSE.LGPLv3
/usr/share/doc/qt5/global
/usr/share/doc/qt5/global/compat.qdocconf
/usr/share/doc/qt5/global/config.qdocconf
/usr/share/doc/qt5/global/externalsites
/usr/share/doc/qt5/global/externalsites.qdocconf
/usr/share/doc/qt5/global/externalsites/external-resources.qdoc
/usr/share/doc/qt5/global/externalsites/qt-webpages.qdoc
/usr/share/doc/qt5/global/externalsites/qtcreator.qdoc
/usr/share/doc/qt5/global/externalsites/rfc.qdoc
/usr/share/doc/qt5/global/fileextensions.qdocconf
/usr/share/doc/qt5/global/html-config.qdocconf
/usr/share/doc/qt5/global/html-footer-online.qdocconf
/usr/share/doc/qt5/global/html-footer.qdocconf
/usr/share/doc/qt5/global/html-header-offline.qdocconf
/usr/share/doc/qt5/global/html-header-online.qdocconf
/usr/share/doc/qt5/global/includes
/usr/share/doc/qt5/global/includes-online
/usr/share/doc/qt5/global/includes-online/search.qdoc
/usr/share/doc/qt5/global/includes/examples-run.qdocinc
/usr/share/doc/qt5/global/macros.qdocconf
/usr/share/doc/qt5/global/manifest-meta.qdocconf
/usr/share/doc/qt5/global/qt-cpp-defines.qdocconf
/usr/share/doc/qt5/global/qt-html-templates-offline.qdocconf
/usr/share/doc/qt5/global/qt-html-templates-online.qdocconf
/usr/share/doc/qt5/global/qt-module-defaults-offline.qdocconf
/usr/share/doc/qt5/global/qt-module-defaults-online-commercial.qdocconf
/usr/share/doc/qt5/global/qt-module-defaults-online.qdocconf
/usr/share/doc/qt5/global/qt-module-defaults.qdocconf
/usr/share/doc/qt5/global/template
/usr/share/doc/qt5/global/template/images
/usr/share/doc/qt5/global/template/images/Qt-dark_gradient.png
/usr/share/doc/qt5/global/template/images/Qt-footer-bg.jpg
/usr/share/doc/qt5/global/template/images/Qt-footer_shadow.png
/usr/share/doc/qt5/global/template/images/Qt-gradient.png
/usr/share/doc/qt5/global/template/images/Qt-header-bg.jpg
/usr/share/doc/qt5/global/template/images/Qt-logo.png
/usr/share/doc/qt5/global/template/images/arrow.png
/usr/share/doc/qt5/global/template/images/arrow_bc.png
/usr/share/doc/qt5/global/template/images/arrow_down.png
/usr/share/doc/qt5/global/template/images/bg_l.png
/usr/share/doc/qt5/global/template/images/bg_l_blank.png
/usr/share/doc/qt5/global/template/images/bg_ll_blank.png
/usr/share/doc/qt5/global/template/images/bg_r.png
/usr/share/doc/qt5/global/template/images/bg_ul_blank.png
/usr/share/doc/qt5/global/template/images/bgrContent.png
/usr/share/doc/qt5/global/template/images/blu_dot.png
/usr/share/doc/qt5/global/template/images/box_bg.png
/usr/share/doc/qt5/global/template/images/breadcrumb.png
/usr/share/doc/qt5/global/template/images/btn_next.png
/usr/share/doc/qt5/global/template/images/btn_prev.png
/usr/share/doc/qt5/global/template/images/bullet_dn.png
/usr/share/doc/qt5/global/template/images/bullet_gt.png
/usr/share/doc/qt5/global/template/images/bullet_sq.png
/usr/share/doc/qt5/global/template/images/bullet_up.png
/usr/share/doc/qt5/global/template/images/feedbackground.png
/usr/share/doc/qt5/global/template/images/header_bg.png
/usr/share/doc/qt5/global/template/images/home.png
/usr/share/doc/qt5/global/template/images/horBar.png
/usr/share/doc/qt5/global/template/images/ico_note.png
/usr/share/doc/qt5/global/template/images/ico_note_attention.png
/usr/share/doc/qt5/global/template/images/ico_out.png
/usr/share/doc/qt5/global/template/images/logo.png
/usr/share/doc/qt5/global/template/images/page.png
/usr/share/doc/qt5/global/template/images/page_bg.png
/usr/share/doc/qt5/global/template/images/spinner.gif
/usr/share/doc/qt5/global/template/images/sprites-combined.png
/usr/share/doc/qt5/global/template/scripts
/usr/share/doc/qt5/global/template/scripts/extras.js
/usr/share/doc/qt5/global/template/scripts/main.js
/usr/share/doc/qt5/global/template/style
/usr/share/doc/qt5/global/template/style/cookiebar-x.png
/usr/share/doc/qt5/global/template/style/doc_search.png
/usr/share/doc/qt5/global/template/style/gsc.css
/usr/share/doc/qt5/global/template/style/icomoon.eot
/usr/share/doc/qt5/global/template/style/icomoon.svg
/usr/share/doc/qt5/global/template/style/icomoon.ttf
/usr/share/doc/qt5/global/template/style/icomoon.woff
/usr/share/doc/qt5/global/template/style/list_arrow.png
/usr/share/doc/qt5/global/template/style/offline.css
/usr/share/doc/qt5/global/template/style/online.css
/usr/share/doc/qt5/global/template/style/theqtcompany.png
/usr/share/qt5
/usr/share/qt5/translations
`

**Comment by kingwill101** [comment]
all the packages were installed from fedoras rawhide repository. If i knew what were the dependencies for the Desktop plugin i could fix the issue
@ricardomv

**Comment by ricardomv** [comment]
Modules should be installed with papyros-shell, did you run make install? What command do you use to start the shell?

**Comment by kingwill101** [comment]
`[kingwill101@kingwill101-desktop build]$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DQML_INSTALL_DIR=lib64/qt5/qml
-- checking for one of the modules 'mobile-broadband-provider-info'

## -- Disabling ModemManager support

-- The following OPTIONAL packages have been found:
- ALSA
- KF5ModemManagerQt (required version >= 5.9.0)
- ModemManager (required version >= 1.0.0)
- PkgConfig

-- The following REQUIRED packages have been found:
- QT5XDG
- PAM
- GreenIsland (required version >= 0.5.9)
- Qt5Core
- Qt5DBus
- Qt5Xml
- Qt5Gui
- Qt5Widgets
- Qt5Qml
- Qt5Quick
- KF5Solid (required version >= 5.8.0)
- KF5Config (required version >= 5.8.0)
- ECM (required version >= 0.0.9)
- KF5Declarative (required version >= 5.8.0)
- KF5NetworkManagerQt (required version >= 5.8.0)
- KF5 (required version >= 5.8.0)
- Qt5Network
- Qt5 (required version >= 5.4.0)
- NetworkManager (required version >= 0.9.8.4)

-- The following OPTIONAL packages have not been found:
- MobileBroadbandProviderInfo , Database of mobile broadband service providers , http://live.gnome.org/NetworkManager/MobileBroadband/ServiceProviders

-- Configuring done
CMake Warning (dev) at 3rdparty/sigwatch/CMakeLists.txt:1 (add_library):
  Policy CMP0063 is not set: Honor visibility properties for all target
  types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "PapyrosSigWatch" of type "STATIC_LIBRARY" has the following
  visibility properties set for CXX:

```
CXX_VISIBILITY_PRESET
VISIBILITY_INLINES_HIDDEN
```

  For compatibility CMake is not honoring them for this target.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at session/CMakeLists.txt:21 (add_executable):
  Policy CMP0063 is not set: Honor visibility properties for all target
  types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "papyros-session" of type "EXECUTABLE" has the following visibility
  properties set for CXX:

```
CXX_VISIBILITY_PRESET
VISIBILITY_INLINES_HIDDEN
```

  For compatibility CMake is not honoring them for this target.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/kingwill101/papyros/papyros-shell/build
[kingwill101@kingwill101-desktop build]$ make && sudo make -j4 install
[  2%] Automatic moc for target PapyrosSigWatch
Generating moc_sigwatch.cpp
[  2%] Built target PapyrosSigWatch_automoc
Scanning dependencies of target PapyrosSigWatch
[  4%] Building CXX object 3rdparty/sigwatch/CMakeFiles/PapyrosSigWatch.dir/sigwatch.cpp.o
[  6%] Building CXX object 3rdparty/sigwatch/CMakeFiles/PapyrosSigWatch.dir/PapyrosSigWatch_automoc.cpp.o
[  8%] Linking CXX static library libPapyrosSigWatch.a
[  8%] Built target PapyrosSigWatch
[ 10%] Automatic moc for target papyrosdesktop
Generating moc_battery.cpp
Generating moc_hardwareengine.cpp
Generating moc_storagedevice.cpp
Generating moc_keyeventfilter.cpp
Generating moc_kquickconfig.cpp
Generating moc_desktopfile.cpp
Generating moc_desktopfiles.cpp
Generating moc_application.cpp
Generating moc_launchermodel.cpp
Generating moc_sound.cpp
Generating moc_mpris2player.cpp
Generating moc_mprisconnection.cpp
Generating moc_notification.cpp
Generating moc_notificationadaptor.cpp
Generating moc_notificationserver.cpp
Generating moc_plugin.cpp
Generating moc_qobjectlistmodel.cpp
Generating moc_sessionmanager.cpp
[ 10%] Built target papyrosdesktop_automoc
Scanning dependencies of target papyrosdesktop
[ 12%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/config/kquickconfig.cpp.o
[ 14%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/launcher/launchermodel.cpp.o
[ 16%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/launcher/application.cpp.o
[ 18%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/keyeventfilter/keyeventfilter.cpp.o
[ 20%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/mpris/mpris2player.cpp.o
[ 22%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/mpris/mprisconnection.cpp.o
[ 24%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/plugin.cpp.o
[ 26%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/notifications/notificationserver.cpp.o
[ 28%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/hardware/storagedevice.cpp.o
[ 30%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/hardware/battery.cpp.o
[ 32%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/hardware/hardwareengine.cpp.o
[ 34%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/desktop/desktopfiles.cpp.o
[ 36%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/desktop/desktopfile.cpp.o
[ 38%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/mixer/pulseaudiomixer.cpp.o
[ 40%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/mixer/alsamixer.cpp.o
[ 42%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/mixer/sound.cpp.o
[ 44%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/session/sessionmanager.cpp.o
[ 46%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/qquicklist/qobjectlistmodel.cpp.o
[ 48%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/papyrosdesktop_automoc.cpp.o
[ 50%] Linking CXX shared library libpapyrosdesktop.so
[ 50%] Built target papyrosdesktop
[ 52%] Automatic moc for target nmplugin
Generating plugin.moc
Generating moc_appletproxymodel.cpp
Generating moc_availabledevices.cpp
Generating moc_connectionicon.cpp
Generating moc_enabledconnections.cpp
Generating moc_enums.cpp
Generating moc_handler.cpp
Generating moc_networkitemslist.cpp
Generating moc_networkmodel.cpp
Generating moc_networkmodelitem.cpp
Generating moc_networkstatus.cpp
[ 52%] Built target nmplugin_automoc
Scanning dependencies of target nmplugin
[ 54%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/appletproxymodel.cpp.o
[ 56%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/availabledevices.cpp.o
[ 58%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/connectionicon.cpp.o
[ 60%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/debug.cpp.o
[ 62%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/enabledconnections.cpp.o
[ 64%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/enums.cpp.o
[ 66%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/handler.cpp.o
[ 68%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/networkitemslist.cpp.o
[ 70%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/networkmodel.cpp.o
[ 72%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/networkmodelitem.cpp.o
[ 74%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/networkstatus.cpp.o
[ 76%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/plugin.cpp.o
[ 78%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/uiutils.cpp.o
4^[[ 80%] Building CXX object modules/Papyros/Network/CMakeFiles/nmplugin.dir/nmplugin_automoc.cpp.o
[ 82%] Linking CXX shared library libnmplugin.so
[ 82%] Built target nmplugin
[ 84%] Automatic moc for target papyros-session
Generating moc_processlauncher.cpp
Generating moc_sessionadaptor.cpp
Generating moc_compositorlauncher.cpp
Generating moc_loginmanager.cpp
Generating moc_sessionmanager.cpp
[ 84%] Built target papyros-session_automoc
Scanning dependencies of target papyros-session
[ 86%] Building CXX object session/CMakeFiles/papyros-session.dir/main.cpp.o
[ 88%] Building CXX object session/CMakeFiles/papyros-session.dir/compositorlauncher.cpp.o
[ 90%] Building CXX object session/CMakeFiles/papyros-session.dir/loginmanager.cpp.o
[ 92%] Building CXX object session/CMakeFiles/papyros-session.dir/processlauncher.cpp.o
[ 94%] Building CXX object session/CMakeFiles/papyros-session.dir/sessionadaptor.cpp.o
[ 96%] Building CXX object session/CMakeFiles/papyros-session.dir/sessionmanager.cpp.o
[ 98%] Building CXX object session/CMakeFiles/papyros-session.dir/papyros-session_automoc.cpp.o
[100%] Linking CXX executable papyros-session
[100%] Built target papyros-session
[  2%] Automatic moc for target papyros-session
[  4%] Automatic moc for target papyrosdesktop
[  6%] Automatic moc for target PapyrosSigWatch
[  8%] Automatic moc for target nmplugin
[  8%] Built target papyros-session_automoc
[  8%] Built target papyrosdesktop_automoc
[  8%] Built target PapyrosSigWatch_automoc
[  8%] Built target nmplugin_automoc
[ 14%] Built target PapyrosSigWatch
[ 30%] Built target papyros-session
[ 70%] Built target papyrosdesktop
[100%] Built target nmplugin
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/launcher
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/launcher/AppDrawer.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/dashboard
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/dashboard/Dashboard.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/panel
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/panel/NotificationCenter.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/panel/SystemCenter.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/lockscreen
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/lockscreen/Lockscreen.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/Compositor.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/images
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/images/papyros-icon.png
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/images/workspaces-expose.svg
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/images/sleep.svg
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/images/papyros-wallpaper.png
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/images/reload.svg
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages/Stage.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages/desktop
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages/desktop/Dock.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages/desktop/DesktopStage.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages/desktop/Launcher.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages/desktop/Panel.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages/desktop/Dash.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages/classic
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages/classic/AppLauncher.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages/classic/ClassicStage.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/stages/classic/Panel.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/OverlayScreen.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/notifications
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/notifications/NotificationsView.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/notifications/NotificationCard.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/notifications/SystemNotifications.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/notifications/SystemNotification.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/KeyLabel.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/HelpOverlay.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/desktop
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/desktop/WindowSwitcher.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/desktop/WorkspacePreview.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/desktop/HotCorner.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/desktop/Desktop.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/desktop/WindowTooltip.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/desktop/WorkspacesView.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/desktop/WorkspaceView.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/desktop/HotCorners.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/PowerDialog.qml
-- Up-to-date: /usr/share/greenisland/shells/io.papyros.shell/Shell.qml
-- Up-to-date: /usr/share/sddm/themes/papyros
-- Up-to-date: /usr/share/sddm/themes/papyros/KeyboardIndicator.qml
-- Up-to-date: /usr/share/sddm/themes/papyros/UserDelegate.qml
-- Up-to-date: /usr/share/sddm/themes/papyros/theme.conf
-- Up-to-date: /usr/share/sddm/themes/papyros/metadata.desktop
-- Up-to-date: /usr/share/sddm/themes/papyros/SessionIndicator.qml
-- Up-to-date: /usr/share/sddm/themes/papyros/images
-- Up-to-date: /usr/share/sddm/themes/papyros/images/sleep.svg
-- Up-to-date: /usr/share/sddm/themes/papyros/images/reload.svg
-- Up-to-date: /usr/share/sddm/themes/papyros/images/wallpaper.png
-- Up-to-date: /usr/share/sddm/themes/papyros/IndicatorRow.qml
-- Up-to-date: /usr/share/sddm/themes/papyros/Main.qml
-- Up-to-date: /usr/share/sddm/themes/papyros/PowerIndicator.qml
-- Up-to-date: /usr/share/wayland-sessions/papyros.desktop
-- Up-to-date: /usr/share/papyros-shell/eglfs/eglfs_kms.json
-- Up-to-date: /usr/lib/qt/qml/GreenIsland/Desktop/qmldir
-- Up-to-date: /usr/lib/qt/qml/GreenIsland/Desktop/TopLevelWindow.qml
-- Up-to-date: /usr/lib/qt/qml/GreenIsland/Desktop/Workspace.qml
-- Up-to-date: /usr/lib/qt/qml/GreenIsland/Desktop/TransientWindow.qml
-- Up-to-date: /usr/lib/qt/qml/GreenIsland/Desktop/PopupWindow.qml
-- Up-to-date: /usr/lib/qt/qml/GreenIsland/Desktop/WindowWrapper.qml
-- Up-to-date: /usr/lib/qt/qml/GreenIsland/Desktop/WindowManager.qml
-- Up-to-date: /usr/lib/qt/qml/GreenIsland/Desktop/WindowAnimation.qml
-- Up-to-date: /usr/lib/qt/qml/GreenIsland/Desktop/WindowListModel.qml
-- Up-to-date: /usr/lib/qt/qml/GreenIsland/Desktop/WindowPreview.qml
-- Up-to-date: /usr/lib/qt/qml/GreenIsland/Desktop/WorkspaceEffect.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Components/qmldir
-- Up-to-date: /usr/lib/qt/qml/Papyros/Components/CrossFadeImage.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Components/AppIcon.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Components/ProgressListItem.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Components/Calendar.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Components/PanelItem.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Desktop/qmldir
-- Up-to-date: /usr/lib/qt/qml/Papyros/Desktop/ShellSettings.qml
-- Installing: /usr/lib/qt/qml/Papyros/Desktop/libpapyrosdesktop.so
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/qmldir
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/NotificationsIndicator.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/DateTimeIndicator.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/OperationsIndicator.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/Indicator.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/IndicatorView.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/ConnectionListItem.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/StorageIndicator.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/NetworkIndicator.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/BatteryIndicator.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/SystemIndicator.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/ActionCenterIndicator.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/MusicPlayerListItem.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/SoundIndicator.qml
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/images
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/images/harddisk.svg
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/images/sleep.svg
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/images/reload.svg
-- Up-to-date: /usr/lib/qt/qml/Papyros/Indicators/images/logout.svg
-- Up-to-date: /usr/lib/qt/qml/Papyros/Network/qmldir
-- Installing: /usr/lib/qt/qml/Papyros/Network/libnmplugin.so
-- Installing: /usr/bin/papyros-session`

**Comment by kingwill101** [comment]
@ricardomv  copying /usr/lib/qt/qml/Papyros to /usr/lib64/qml fixes the issue but goes on to give 

file:///usr/share/greenisland/shells/io.papyros.shell/Shell.qml:118:5: Type Desktop unavailable
file:///usr/share/greenisland/shells/io.papyros.shell/desktop/Desktop.qml:23:1: module "GreenIsland.Desktop" is not installed

**Comment by ricardomv** [comment]
QML_INSTALL_DIR=lib64/qt5/qml should not work here you need to provide the full path /usr/lib64/qt5/qml

**Comment by kingwill101** [comment]
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DQML_INSTALL_DIR=/usr/lib64/qt5/qml

produces the same error

**Comment by iBelieve** [comment]
@glenfordwilliams Try erasing your build folder. CMake might cache variables.

**Comment by kingwill101** [comment]
@iBeliever  thanks that worked...
