### ISSUE TITLE
Source directory does not contain CMakeLists.txt

### ISSUE THREAD

**Issue by alexkreidler** [papyros/papyros-shell#163]
I installed papyros-shell via pacman.

```
CMake Error: The source directory "/lib/qt/qml" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

I followed all the installation instructions in readme.md, but I can't get it to compile.

**Comment by iBelieve** [comment]
How are you running Cmake? Cmake shouldn't be necessary if you installed binary packages via pacman.

**Comment by alexkreidler** [comment]
This was a mistake on my part for not installing the right way.
