### ISSUE TITLE
Network indicator [$15]

### ISSUE THREAD

**Issue by iBeliever** [papyros/papyros-shell#17]
We can probably use [libnm-qt](https://projects.kde.org/projects/extragear/libs/libnm-qt), which is a Network Manager wrapper in Qt.

**Comment by CameronNemo** [comment]
@naguirre You would ideally have both for users who want to use connman in place of Network Manager. But most distros/people use network manager so it is probably the best option.

**Comment by iBelieve** [comment]
This is fixed by @ricardomv's work that I merged in d7f4629336064fbe7647f733a5f95415c89b7d18.

@ricardomv Go ahead and claim the bounty for your work on the network indicator :+1:
