### ISSUE TITLE
Create a Papyros Gitter (gitter.im) Chat Room 

### ISSUE THREAD

**Issue by SuicSoft** [papyros/papyros-shell#172]

**Comment by alexkreidler** [comment]
There already is one at https://gitter.im/papyros/papyros. This is for the
Papyros shell, but if you are looking for the material design Gitter room,
you can find it at https://gitter.im/papyros/qml-material.

**Comment by SuicSoft** [comment]
@Tim15  How about adding a readme badge?

**Comment by IdrissDimson** [comment]
This'll take a good 50 seconds. I'm timing

**Comment by iBelieve** [comment]
@VirusKA :smile:

**Comment by IdrissDimson** [comment]
shame on you. gotta do better than that.
