### ISSUE TITLE
CSD decorations branch fails to compile on Antergos [$10 awarded]

### ISSUE THREAD

**Issue by ctnlaring** [papyros/papyros-shell#175]
I had the develop branch working but then I decided to try and get the decorations working. 
Error: https://docs.google.com/document/d/1SJLQBU9ZAqkRS221lZHDF548zwptAVxSZ567apj9hYQ/edit?usp=sharing
##

**Comment by Collinthegeek** [comment]
It seems to be missing the file "/usr/lib/qt/plugins/wayland-decoration-client/libmaterial.so"

**Comment by iBelieve** [comment]
I'm working on getting this merged into `develop` in both the shell and framework. That'll fix any bugs compiling.

**Comment by iBelieve** [comment]
This is no longer relevent as we won't be using CSDs in Qt (see #98).
