### ISSUE TITLE
The launcher should get applications from ~/.local/share/applications [$10 awarded]

### ISSUE THREAD

**Issue by ctnlaring** [papyros/papyros-shell#176]
##

**Comment by ctnlaring** [comment]
Chrome apps and other user specific applications go here

**Comment by ctnlaring** [comment]
I assume it currently only gets them from /usr/share/applications right?

**Comment by RyanSquared** [comment]
Another way to fix this - as I know some desktop environments do - is to make an environmental variable for the application path. Something like `APPPATH`?

**Comment by iBelieve** [comment]
Thanks for reporting the bug!
