### ISSUE TITLE
The launcher should open when the windows key is pressed. [$10 awarded]

### ISSUE THREAD

**Issue by ctnlaring** [papyros/papyros-shell#177]
It looks like it's trying to but something's broken.

qml: Key pressed 16777250 
file:///usr/share/greenisland/shells/io.papyros.shell/Shell.qml:193: ReferenceError: helpTimer is not defined
file:///usr/share/greenisland/shells/io.papyros.shell/launcher/AppDrawer.qml:280: ReferenceError: selected is not defined
##

**Comment by iBelieve** [comment]
Thanks for the bug report @Collinthegeek!
