### ISSUE TITLE
The display is not scaled properly

### ISSUE THREAD

**Issue by alexkreidler** [papyros/papyros-shell#178]
When I run `papyros-session`, the display is huge and I only see a small corner of it. Same thing with the sddm.

**Comment by kingwill101** [comment]
Did u set a fakescreen profile?

**Comment by ctnlaring** [comment]
Are you running within another desktop environment or by itself?

**Comment by alexkreidler** [comment]
I did not use a fakescreen profile, and I am running it in KDE. Another note: When I use a different monitor it works perfectly. I think the issue was with how GreenIsland/Wayland (or something upstream) reacts to displays that say they have one resolution but actually have another. For example, anything on my screen (KDE, the plain old arch terminal, Windows) gets cut off, like the monitor is saying it has a bigger resolution than it actually does. It would be better if Papyros scaled properly even with incompetent screens, but for now I'd say this is a low-priority issue.
