### ISSUE TITLE
Can't start shell from VT or DM

### ISSUE THREAD

**Issue by riesinger** [papyros/papyros-shell#179]
I've installed the shell via pacman and starting it from within another desktop environment (a terminal emulator) works quite well.
However, if I try to start it from LightDM, it won't do anything (the LightDM background will be shown indefinitely long) and if I try to start it from a TTY, my screen will turn black for a second and then I loose the  input signals to both of my monitors. It does not matter if I start it via `papyros-session` or `greenisland --platform eglfs --shell io.papyros.shell`

I have a radeon r5 265 video card and use the open source drivers.
I don't know how to debug this, as the only thing I can do to recover my computer is to reboot it.

Does anybody have a clue why this happens and how to fix it?

(BTW, I'm not a native speaker, so sorry for mistakes)

**Comment by iBelieve** [comment]
Thanks for the bug report! I've been looking into this bug, and have found the following things:
1. `papyros-session` works fine from inside GNOME (so not happening in all configurations).
2. `greenisland --platform eglfs --shell io.papyros.shell` works from inside GNOME (so not specific to eglfs).
3. `greenisland` works fine from a VT (so not a greenisland issue).
4. `papyros-session` does not work from a VT or DM.
5. `greenisland --platform eglfs --shell io.papyros.shell` does not work from a VT.

I've tried most of those condititions from both a QEMU VM and from my main Arch system.

Based on these findings, something (probably a library we're using, maybe a KFramework) seems to require something that only exists in a running session. My next step is to strip out everything and start adding feature after feature back in until we get this fixed.

**Comment by riesinger** [comment]
This exactly represents my findings (though I first tried it in i3). The problem with this was that I could not run apps in papyros-session, they always opened in i3. I will try this later in GNOME.

**Comment by iBelieve** [comment]
My guess at the problem seems to be correct. I ripped out everything from the shell and added a single button to kill the session, and that worked fine from both a VT and GDM. Now I'll start adding in features one at a time until I hit the bug again.

**Comment by riesinger** [comment]
Great!

**Comment by iBelieve** [comment]
This should be fixed now! Suprisingly, the backend for the sound indicator was causing the freezing, so I disabled it for now. I know it used to work, so I'm not sure what went wrong.

**Comment by riesinger** [comment]
Good job! Thank you :)
