### ISSUE TITLE
Gtk tooltips sometimes get stuck and show in the top left corner of a window

### ISSUE THREAD

**Issue by iBelieve** [papyros/papyros-shell#188]
![screenshot from 2015-12-10 21-28-29](https://cloud.githubusercontent.com/assets/3230912/11735290/2b843596-9f85-11e5-992c-5a0cf8956670.png)

**Comment by IdrissDimson** [comment]
Man i want to test this OS out so bad :P

**Comment by ctnlaring** [comment]
http://papyros.io/download

**Comment by iBelieve** [comment]
I'm going to try to reproduce this upstream in the sample Green Island compositor. If I can, I'll file an upstream bug report in the hopes that it can be fixed there.

**Comment by IdrissDimson** [comment]
so is it another upstream issue?

**Comment by iBelieve** [comment]
Yes, this was an upstream issue and is fixed by updating to the latest GreenIsland code.
