### ISSUE TITLE
Error building from repo source

### ISSUE THREAD

**Issue by c0d3st0rm** [papyros/papyros-shell#189]
I've probably missed something obvious so I apologize in advance if I have. Built GreenIsland from source in Arch VM, now I'm trying to build the shell, but I get a (seemingly) GreenIsland-related error after running `make`:

```
[  2%] Automatic moc for target PapyrosSigWatch
[  2%] Built target PapyrosSigWatch_automoc
[  8%] Built target PapyrosSigWatch
[ 10%] Automatic moc for target papyrosdesktop
[ 10%] Built target papyrosdesktop_automoc
[ 12%] Building CXX object modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/launcher/application.cpp.o
/home/joe/git/papyros-shell/modules/Papyros/Desktop/launcher/application.cpp:20:42: fatal error: GreenIsland/ApplicationManager: No such file or directory
compilation terminated.
modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/build.make:254: recipe for target 'modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/launcher/application.cpp.o' failed
make[2]: *** [modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/launcher/application.cpp.o] Error 1
CMakeFiles/Makefile2:362: recipe for target 'modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/all' failed
make[1]: *** [modules/Papyros/Desktop/CMakeFiles/papyrosdesktop.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

Like I said, I've probably missed something, but I don't have a clue as to what.

**Comment by ricardomv** [comment]
We currently only support greenisland v0.6 so you need to install that version.

**Comment by c0d3st0rm** [comment]
Note taken, but is that the cause of the error?

**Comment by ricardomv** [comment]
I think so.

**Comment by c0d3st0rm** [comment]
We'll see. So shall I try and build the 0.6 source and then install it like normal for a built package?

**Comment by ricardomv** [comment]
you can use this PKGBUILD for arch https://github.com/papyros/repository/blob/testing/packages/greenisland/PKGBUILD
but keep in mind greenisland doesn't work on virtual box (i don't know if that's what you're using) 
Have you tried installing using the instructions on the site http://papyros.io/download/index.html ?

**Comment by c0d3st0rm** [comment]
I'm am using virtualbox I'm afraid, so there's an issue right there - why doesn't it work? As a note, I'm using KVM with it too. Tried installing that package, didn't work I believe, so I am trying using source builds instead.

**Comment by ricardomv** [comment]
This is the related issue from upstream greenisland/greenisland/issues/136 i think there is nothing we can do this is an issue with virtual box.

**Comment by ricardomv** [comment]
Here is the bug report in vbox https://www.virtualbox.org/ticket/13471

**Comment by iBelieve** [comment]
I'm going to close this out, as we have another ticket for updating to GreenIsland 0.7. For reference on running in a VM, see https://github.com/papyros/papyros-shell/wiki/Running-in-a-Virtual-Machine.
