### ISSUE TITLE
Modifier keys are not passed to applications

### ISSUE THREAD

**Issue by iBelieve** [papyros/papyros-shell#192]
For example, when I have Files open and I type `Ctrl+L`, I expect the path bar to show, but instead it opens the quick search with `L` entered in the text field.

**Comment by iBelieve** [comment]
Reproduced and filed upstream as greenisland/greenisland#158.

**Comment by iBelieve** [comment]
Just chatted with the Green Island developer in IRC. Here's the conversation we had:

> iBeliever: plfiorini: Hey, have you had a chance to look into https://github.com/greenisland/greenisland/issues/158 yet? It seems like a pretty critical bug and I’d love to see that fixed as soon as possible.
> [11:21am] plfiorini: iBeliever: yes, it needs qt 5.6
> [11:22am] iBeliever: plfiorini: Ah, bummer. Could you update the README to mention that? Also, will Green Island even compile with Qt 5.6? I saw https://github.com/greenisland/greenisland/issues/155
> [11:23am] plfiorini: iBeliever: yep i'm porting to qt 5.6, a lot has changed
> [11:24am] iBeliever: plfiorini: So basically, to fully use the keyboard in apps, I need to use Qt 5.6, but currently, you can’t even use Green Island with Qt 5.6?
> [11:25am] plfiorini: iBeliever: yep currently it doesn't work, i'm porting the code in another branch not yet merged with master
> [11:25am] iBeliever: plfiorini: Ok. Is that branch on GitHub?
> [11:26am] plfiorini: iBeliever: no because it gets force pushed frequently
> [11:27am] iBeliever: plfiorini: Well, I always push my work to feature branches, even though I often rebase and force push. But anyway, is it possible to fix the bug on Qt 5.5? I thought modifier keys used to work in Green Island.
> …
> [11:36am] plfiorini: iBeliever: modifier keys were broken since april (https://codereview.qt-project.org/#/c/110970/)
> [11:36am] plfiorini: the fix went into qt 5.6
> …
> [11:46am] iBeliever: plfiorini: Thanks for explaining the bug and answering my questions. Enjoy your Christmas vacation!

Basically, we need Qt 5.6 to fix this bug, but Green Island doesn't fully work with Qt 5.6.

**Comment by IdrissDimson** [comment]
so this means we can mark this as complete? :)

**Comment by iBelieve** [comment]
Right. This is fixed by https://github.com/papyros/repository/commit/4e79489c147c3638e18b1ab8c9c4d0978ec0feb3. We ended up patching Qt 5.5 with the fix from Qt 5.6.
