### ISSUE TITLE
Material on Qt Widgets

### ISSUE THREAD

**Issue by raynerd** [papyros/papyros-shell#2]
Hello you can count on me for develop a Qt Style that mimics Material Design, I'm pretty confortable with this task and I believe this project will have an excelent future. I'v already done a Qt style before called Meterial but it isn't related to google Material at all, you can found it here https://github.com/raynerd/styles-stuff. Send me a message at raynerd@gmx.com if you are interested. best regards

**Comment by IdrissDimson** [comment]
shouldn't this be closed?

**Comment by iBelieve** [comment]
Yes, there hasn't been any discussion on this, and we have a QtQuick Controls style, so I'll close this for now.

@raynerd Please reopen this if you're interested in helping with a Gtk or Qt theme for Material Design. Thanks!
