### ISSUE TITLE
Question:  Compiling on Debian

### ISSUE THREAD

**Issue by JosephMillsAtWork** [papyros/papyros-shell#202]
## Summary

So I have compiled and got all the things that the README.md file says that I should get. 

I am a little bit confused about Green Island I see that in the cmakelist.txt it is asking for something larger then 
    0.5.94

But after building green island to (branch that is talked about in the README.md) 
1. after looking at CmakeList.txt I noticed that the versions do not match  

``` cmake
find_package(GreenIsland 0.6.90 REQUIRED)
```

No big deal

``` cmake
find_package(GreenIsland 0.5.94 REQUIRED)
```
1. Can not find the configs for cmake no big deal 

```
set(GreenIsland '/usr/lib/cmake/GreenIsland/')
```
1. launchermodel.cpp is calling  GreenIsland/Server/ but there is no folder called that.  No big deal make it and place includes.  (this was done a couple of times)
2.  can not find the server lib 

``` cmake
[100%] Linking CXX shared library libpapyrosdesktop.so
/usr/bin/ld: cannot find -lGreenIsland::Server
```
#### greenisland.build

``` bash
#!/bin/bash
cmake ../ \
-DCMAKE_INSTALL_PREFIX=/usr \
-DLIB_INSTALL_DIR=lib/ \
-DLIBEXEC_INSTALL_DIR=lib/ \
-DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
-DCMAKE_BUILD_TYPE=RelWithDebInfo
```
#### papyos-shell.build

``` bash
#!/bin/bash
cmake ../ \
-DCMAKE_INSTALL_PREFIX=/usr
```
## Question

Do I just need a different version of GreenIsland or a different commit of the shell ?  

Thanks for your time.

**Comment by JosephMillsAtWork** [comment]
NVM 

![pap](https://cloud.githubusercontent.com/assets/8931995/12008316/5e1d0fb8-abe8-11e5-8c70-895c26dfe782.png)

**Comment by iBelieve** [comment]
Apologies, the README instructions regarding GreenIsland were outdated. Sorry if this caused any confusion! It looks like you got it working though - can this issue be closed?

**Comment by JosephMillsAtWork** [comment]
Yes this can now be closed.  Thanks for your hard work.  
If you like I could make a Wiki for installing to debian based systems. 

Again thanks.

**Comment by Fabi** [comment]
I just tested the wiki for Debian based systems on Debian 8. First one repo is missing there and it doesnt matter which dep you try to build, it just Fails on a clean Debian system
