### ISSUE TITLE
hot corner overlaps window buttons

### ISSUE THREAD

**Issue by kingwill101** [papyros/papyros-shell#206]
![screenshot_20151231_080655](https://cloud.githubusercontent.com/assets/1114368/12064606/88f33bd0-af95-11e5-9586-b9ee8425c0e2.png)

**Comment by alexkreidler** [comment]
We really need to redesign and improve the hot corners.

**Comment by iBelieve** [comment]
@Tim15 Indeed, see #130.

**Comment by iBelieve** [comment]
I'm closing this as a duplicate of the above issue.
