### ISSUE TITLE
tracking running apps

### ISSUE THREAD

**Issue by glenfordwilliams** [papyros/papyros-shell#21]
What is the best way to keep track of all apps installed/running?

**Comment by ricardomv** [comment]
You have to be more specific, what are you trying to achieve? The shell is not complete so not all the functionalities are implemented.

**Comment by iBelieve** [comment]
Tracking open windows is implemented now. Tracking windows grouped as apps will be implemented in #70.

**Comment by kingwill101** [comment]
@iBeliever  where can i find the implementation?
