### ISSUE TITLE
build failed main.cpp:316: Parse error at "IID"

### ISSUE THREAD

**Issue by ghost** [papyros/papyros-shell#213]
This is a new arch installation on a Virtual Box. I installed all of the dependencies and it was all good. but then I get this error when I try to build the papyros-shell.

![input](https://cloud.githubusercontent.com/assets/6195060/12134932/57216210-b43d-11e5-8818-80c3a6e571ed.png)

**Comment by ghost** [comment]
hi

**Comment by Thisuu** [comment]
@lordadamson  The same bug is reported at https://github.com/papyros/papyros-shell/issues/203
I hope they'll look into it..

**Comment by ghost** [comment]
Oh thanks a lot buddy. I'll close this one and let them know the bug affects me there.
