### ISSUE TITLE
http://dash.papyros.io/repos/ is a 404 page

### ISSUE THREAD

**Issue by Jack-Works** [papyros/papyros-shell#239]
This url is provided by papyros.io
##

**Comment by denysvitali** [comment]
Can confirm.
Is this project dead?

**Comment by GRA0007** [comment]
This is true. Are they still working on it?

**Comment by minkeykumar** [comment]
unable to download papyros shell on arch linux. Please refer below for error in pacman

error: failed retrieving file 'papyros.db' from dash.papyros.io : Connection timed out after 10000 milliseconds
error: failed to update papyros (download library error)
:: Starting full system upgrade...
error: failed to prepare transaction (could not find database)

**Comment by ctnlaring** [comment]
Papyros has merged with the Liri project. http://github.com/lirios
