### ISSUE TITLE
Can't install on ArchLinux

### ISSUE THREAD

**Issue by bryce-happel-walton** [papyros/papyros-shell#240]
This happens whenever I try to run the pacman commands

![image](https://cloud.githubusercontent.com/assets/22112182/26523798/038610ac-42ed-11e7-8347-ffe99cd52f16.png)

**Comment by SamuelM333** [comment]
Dude this project is more dead than COBOL lol. Don't expect any answer from the developers soon.

**Comment by ace0k** [comment]
papyros now is https://liri.io/ as I understood, but it is also in alpha
