### ISSUE TITLE
papyros-shell and EGL_WL_bind_wayland_display

### ISSUE THREAD

**Issue by fedya** [papyros/papyros-shell#30]
I'm trying to run papyros-shell on the ARM board (sabre lite)
and i got this.
Looks like i need to build some package with option like --enable-wayland
but i don't know what package.
Any suggestions?

[root@localhost ~]# DISPLAY=:0 papyros-shell 
libEGL warning: DRI2: failed to authenticate
QtCompositor: Failed to initialize EGL display. There is no EGL_WL_bind_wayland_display extension.
qrc:/qml/main.qml:28:9: Cannot assign to non-existent property "accentColor"
QObject::connect: Cannot connect QmlCompositor::windowAdded(QVariant) to (null)::windowAdded(QVariant)
QObject::connect: Cannot connect QmlCompositor::windowResized(QVariant) to (null)::windowResized(QVariant)
Segmentation fault (core dumped)

**Comment by fedya** [comment]
i rebuilt qt5-qtbase with es2 option

**Comment by Collinthegeek** [comment]
@fedya can you tell me how you did this?

**Comment by iBeliever** [comment]
Take a look at #20, which is the same or similar problem.

**Comment by fedya** [comment]
@Collinthegeek https://abf.io/openmandriva/qt5-qtbase/blob/master/qt5-qtbase.spec#lc-1105
