### ISSUE TITLE
undefined variables

### ISSUE THREAD

**Issue by glenfordwilliams** [papyros/papyros-shell#32]
hey havent been around for a while but im happy to see the progress we are making so far. I noticed that that my latest clone of the papyros-shell is complaining about alot of values which seem non existing on this side of the project .
 @iBeliever 

qrc:/qml/components/ProgressListItem.qml:104:17: Cannot assign to non-existent property "alwaysShow"
qrc:/qml/main.qml:25:9: Cannot assign to non-existent property "accentColor"
qrc:/qml/Shell.qml:90:5: Type Lockscreen unavailable
qrc:/qml/SystemCenter.qml:59:13: Cannot assign to non-existent property "valueText"
qrc:/qml/SystemCenter.qml:70:13: Cannot assign to non-existent property "secondaryItem"

**Comment by iBeliever** [comment]
Can you pull the latest code from our various repositories and try again? The v0.0.2 tag for all repositories should be a known-working combination.

**Comment by glenfordwilliams** [comment]
still having problems 

Starting /home/kingwill101/Documents/git/papyros-shell/papyros-shell...
qrc:/qml/Shell.qml:26:1: "dashboard": no such directory
/home/kingwill101/Documents/git/papyros-shell/papyros-shell exited with code 0

Starting /home/kingwill101/Documents/git/papyros-shell/papyros-shell...
qrc:/qml/Shell.qml:149:5: KeyEventFilter is not a type
/home/kingwill101/Documents/git/papyros-shell/papyros-shell exited with code 0

**Comment by nil1511** [comment]
@glenfordwilliams generate qrc file again with by 
```./qrc.py qml images > papyros-shell.qrc```
and then 
```
qmake.
make
```
 then the error regarding dashboard should be gone

**Comment by glenfordwilliams** [comment]
thanks but now i still have problems with 

Starting /home/kingwill101/Documents/git/papyros-shell/papyros-shell...
qrc:/qml/Shell.qml:149:5: KeyEventFilter is not a type
/home/kingwill101/Documents/git/papyros-shell/papyros-shell exited with code 0


and i see where its gonna be the same for

    Sound {
        id: sound

        property string iconName: sound.muted ? "av/volume_off"
                                  : sound.master <= 33 ? "av/volume_mute"
                                  : sound.master >= 67 ? "av/volume_up"
                                  : "av/volume_down"
    }

**Comment by iBeliever** [comment]
@glenfordwilliams Please try pulling down the latest code from qml-desktop and installing that. The Sound and KeyEventFilter classes were just recently added.
