### ISSUE TITLE
various issues

### ISSUE THREAD

**Issue by ricardomv** [papyros/papyros-shell#33]
Starting the shell using the binary i get:
`qrc:/qml/Shell.qml:26:1: "dashboard": no such directory`
I guess something is missing in the qrc file

Other issues are:
`file:///home/ricardo/code/git/quantum-shell/qml/Shell.qml:276:5: Sound is not a type`
`file:///home/ricardo/code/git/quantum-shell/qml/Shell.qml:149:5: KeyEventFilter is not a type`

the last one might be my fault as i might need to have something installed for it to work.

**Comment by ricardomv** [comment]
Yup for the last one i had to update qml-desktop

**Comment by iBeliever** [comment]
Both of those were pushed to qml-desktop along with the changes to the shell. Is this working and closable now?

**Comment by ricardomv** [comment]
you need to add `<file>qml/dashboard/Dashboard.qml</file>` to the qrc file

**Comment by ricardomv** [comment]
seems to be fixed in the latest commit. Thanks
