### ISSUE TITLE
Compiling the shell fails

### ISSUE THREAD

**Issue by Joannis** [papyros/papyros-shell#34]
I've been trying to get this to work for a while now but I keep running into; 

../papyros-shell/src/main.cpp: In constructor `QmlCompositor::QmlCompositor()`:
../papyros-shell/src/main.cpp:71:25: error: `addDefaultShell` was not declared in this scope
           addDefaultShell();
                                     ^

Am I overlooking something? I installed the correct packages and this seems to be a problem with "qt5-wayland-dev-git".

**Comment by 29jm** [comment]
Did you change the PKGBUILD like the comment said here: https://aur.archlinux.org/packages/qt5-wayland-dev-git/ ? I had a different error before I did that

**Comment by ricardomv** [comment]
sorry it took so long for someone to answer this, but it's in the README.md you need to enable qtcomposiror when building qtwayland
