### ISSUE TITLE
qml references need to be updated after commit 0dafe4f9b496a03be4b6ed7d50c80550c6de3654

### ISSUE THREAD

**Issue by mihailescu2m** [papyros/papyros-shell#37]
In 0dafe4f9b496a03be4b6ed7d50c80550c6de3654 qmls are moved around, but Shell.qml references the old location.

**Comment by 29jm** [comment]
Yes and papyros-shell.qrc hasn't been updated either so qmake fails. I can provide a patch? I never made a pull request before but I can try.
