### ISSUE TITLE
Can't exit shell when run as a wayland compositor

### ISSUE THREAD

**Issue by 29jm** [papyros/papyros-shell#40]
When I do Control+Alt+Backspace, Qt.quit() is called from QML, but it does nothing and prints the message:
```
Signal QDeclarativeEngine::quit() emitted, but no receivers connected to handle it
```
Note that it only does that when I run directly from the tty, not with platform -xcb from X
I fixed it by adding
```cpp
QObject::connect(compositor.rootContext()->engine(), SIGNAL(quit()), &app, SLOT(quit()));
```
to src/main.cpp.
Didn't want to open a pull request just for that, I hope it's alright

**Comment by boghison** [comment]
@29jm Please go ahead and open one, every contribution matters :)

**Comment by 29jm** [comment]
@boghison Ok, I just did.

**Comment by boghison** [comment]
@29jm Thank you :)
