### ISSUE TITLE
Material.Desktop does not exists

### ISSUE THREAD

**Issue by Mr1Penguin** [papyros/papyros-shell#42]
I installed all requested packages but Shell.xml can't find Material.Desktop. Just noticed that there is no module with name 'Desktop' in qml-materials.
Shell ouput: qrc:/qml/Shell.qml:21:1: module "Material.Desktop" is not installed

**Comment by boghison** [comment]
@Mr1Penguin  Did you install [it](https://github.com/papyros/qml-desktop)?

**Comment by Mr1Penguin** [comment]
I didn't.
Now it works. Thanks. I assume it will be a good idea to add this to Readme.md. Or i can(must?) do it myself?

**Comment by boghison** [comment]
@Mr1Penguin Yeah, feel free to submit a PR :)
