### ISSUE TITLE
QtCompositor: Failed to initialize EGL display. Could not get EglDisplay for window.

### ISSUE THREAD

**Issue by crutchcorn** [papyros/papyros-shell#46]
Installed papyros-shell-git via yaourt, everything worked fine, but when I run papyros-shell, I get this error.
QtCompositor: Failed to initialize EGL display. Could not get EglDisplay for window.
qrc:/qml/Shell.qml:119:9: Type Dock unavailable
qrc:/qml/launcher/Dock.qml:65:14: Type AppIcon unavailable
qrc:/qml/components/AppIcon.qml:177:5: Type Tooltip unavailable
qrc:/qml/components/Tooltip.qml:46:5: Cannot assign to non-existent property "radius"
![screenshot from 2015-02-26 16 53 24](https://cloud.githubusercontent.com/assets/9100169/6405408/f15480fe-bdd7-11e4-9bf8-ecb5c9ec653f.png)

**Comment by ricardomv** [comment]
can you test this with the fix/errors branch?

**Comment by crutchcorn** [comment]
It works!

**Comment by crutchcorn** [comment]
Although, I keep getting 
'file:///usr/lib/qt/wml/Material/PopupBase.qml:##: TypeError: Type error'

**Comment by ricardomv** [comment]
We are still catching up with qml-material changes

**Comment by crutchcorn** [comment]
Sounds good. :) Thank you for the info!

**Comment by ricardomv** [comment]
fix/errors has been merged
