### ISSUE TITLE
error: no matching function for call to QWaylandQuickCompositor::QWaylandQuickCompositor

### ISSUE THREAD

**Issue by fedya** [papyros/papyros-shell#48]
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.92661
+ umask 022
+ cd /home/fedya/papyros-shell/BUILD
+ cd papyros-shell-0.0.0-20150303
+ '[' 1 -eq 1 ']'
+ '[' 1 -eq 1 ']'
+ CPPFLAGS='-Oz -Wa,--compress-debug-sections -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fPIC -DPIC -fPIC'
+ export CPPFLAGS
+ /usr/bin/qmake-qt5 libsuff=64 'QMAKE_CFLAGS=-Oz -Wa,--compress-debug-sections -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fPIC -DPIC -fPIC' 'QMAKE_CXXFLAGS=-Oz -Wa,--compress-debug-sections -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fPIC -DPIC -fPIC' QMAKE_CXXFLAGS_RELEASE= 'QMAKE_LFLAGS= -Wl,--no-undefined ' papyros-shell.pro
+ /usr/bin/make -j8 -O
/usr/lib64/qt5/bin/moc -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_COMPOSITOR_LIB -DQT_COMPOSITOR_WAYLAND_GL -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/lib64/qt5/mkspecs/linux-g++-64 -I/home/fedya/papyros-shell/BUILD/papyros-shell-0.0.0-20150303 -I/home/fedya/papyros-shell/BUILD/papyros-shell-0.0.0-20150303/src -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtCompositor -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/4.9.3 -I/usr/include/c++/4.9.3/x86_64-mandriva-linux-gnu -I/usr/include/c++/4.9.3/backward -I/usr/lib64/gcc/x86_64-mandriva-linux-gnu/4.9.3/include -I/usr/local/include -I/usr/include src/qmlcompositor.h -o moc_qmlcompositor.cpp
/usr/lib64/qt5/bin/rcc -name papyros-shell papyros-shell.qrc -o qrc_papyros-shell.cpp
g++ -c -Oz -Wa,--compress-debug-sections -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fPIC -DPIC -fPIC -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_COMPOSITOR_LIB -DQT_COMPOSITOR_WAYLAND_GL -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Isrc -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtCompositor -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++-64 -o qmlcompositor.o src/qmlcompositor.cpp
src/qmlcompositor.cpp: In constructor 'QmlCompositor::QmlCompositor()':
src/qmlcompositor.cpp:45:28: error: no matching function for call to 'QWaylandQuickCompositor::QWaylandQuickCompositor(const char [14], QFlags<QWaylandCompositor::ExtensionFlag>)'
     , m_fullscreenSurface(0)
                            ^
src/qmlcompositor.cpp:45:28: note: candidates are:
In file included from src/qmlcompositor.h:44:0,
                 from src/qmlcompositor.cpp:41:

**Comment by iBeliever** [comment]
There was a recent change in QtCompositor. You need to re-built it from the 5.5 branch. If you're not willing to do that, revert the [selected line in this commit](https://github.com/papyros/papyros-shell/commit/3247afa108c3383809e15482e5cfce6d5105dfe2#diff-5dd702b5160f17b1de6dc1b88f1953b7L44) locally.

**Comment by iBeliever** [comment]
Closing now as there has been no further discussion on this issue and the compiler error is solved by the Qt 5.5 alpha (and development branches).
