### ISSUE TITLE
Maximizing windows

### ISSUE THREAD

**Issue by boghison** [papyros/papyros-shell#5]
To give the shell a more "material" feeling we could make a wave animation that changes the color to the header color of the window for the panel. From the Window.qml code I understand that the header is hidden when the window is maximized, yes? Anyway, I can start working on it (I've already written the maths necessary to correctly show it) if you agree to do this. I was also thinking of using the x and y coordinates from the maximizing drag and the wave would be like a notification that the user will be maximizing the window. On double click the circle will start growing from the middle. So, what do you think?

**Comment by iBelieve** [comment]
Closing as we don't have a top bar right now. We'll re-evaluate this once we start on the modern desktop layout again.
