### ISSUE TITLE
Makefile:426: recipe for target 'qmlcompositor.o' failed

### ISSUE THREAD

**Issue by crutchcorn** [papyros/papyros-shell#50]
When I run make I run into this issue:
/usr/include/qt/QtCompositor/qwaylandquickcompositor.h:56:5: note:   no known conversion for argument 1 from ‘const char [14]’ to ‘QQuickWindow*’
/usr/include/qt/QtCompositor/qwaylandquickcompositor.h:53:27: note: QWaylandQuickCompositor::QWaylandQuickCompositor(const QWaylandQuickCompositor&)
 class Q_COMPOSITOR_EXPORT QWaylandQuickCompositor : public QWaylandCompositor
                           ^
/usr/include/qt/QtCompositor/qwaylandquickcompositor.h:53:27: note:   candidate expects 1 argument, 2 provided
Makefile:426: recipe for target 'qmlcompositor.o' failed
make: *** [qmlcompositor.o] Error 1

**Comment by iBeliever** [comment]
Check out #48. You need to update to the latest version of Qt 5.5, or revert the affected line.
