### ISSUE TITLE
The desktop failed to materialize 

### ISSUE THREAD

**Issue by alex285** [papyros/papyros-shell#51]
qrc:/qml/Shell.qml:119:9: Type Dock unavailable
qrc:/qml/launcher/Dock.qml:65:14: Type AppIcon unavailable
qrc:/qml/components/AppIcon.qml:51:17: Cannot assign to non-existent property "onClicked"

On Arch from Papyros repository, version  Papyros 0.0.5.3

**Comment by iBeliever** [comment]
Can you check the version of `qml-material` you have installed? It should be `0.0.5-2`. (You can run `pacman -Qi qml-material` to get that information).

**Comment by alex285** [comment]
I had 0.0.4-1. Updating fixed the issue. Thanks!

**Comment by iBeliever** [comment]
Great, glad that fixed your problem!

**Comment by Collinthegeek** [comment]
I don't get this issue using the repository but do with the github version.
