### ISSUE TITLE
Shell hangs with possible QQuickItem::polish() loop

### ISSUE THREAD

**Issue by Collinthegeek** [papyros/papyros-shell#52]
I'm on arch Linux, Everything installed fine with no errors. I get this error when I run, I see a blue screen that says welcome but nothing works and I have to ^c to kill it. I fixed it temporarily by moving the qml folder to / but it only worked once and doesn't work again.

http://pastebin.com/4K9QADww

**Comment by Collinthegeek** [comment]
I managed to fix this in a REALLY REALLY bad way, I moved the qml folder to /

**Comment by djmaze** [comment]
Have the same issue. Only about 50% of my attempts to start papyros-shell are successful. I am on Arch Linux, too.

**Comment by Collinthegeek** [comment]
Same, it works occasionally

**Comment by juston-li** [comment]
Works maybe once in 15-20 tries for me. Also running Arch

**Comment by iBelieve** [comment]
The shell now launches 100% of the time, no random problems. The main issue right now is interacting with windows usually crashes the app and often the shell as well. This is filed as an upstream bug in Green Island (see greenisland/greenisland#76). Please check out the latest code from the `develop` branch.
