### ISSUE TITLE
Papyros-Shell does not work on Weston with the fullscreen-shell.so

### ISSUE THREAD

**Issue by n3rdopolis** [papyros/papyros-shell#53]
It seems that when I try to start papyros-shell on a Weston server that has been called with

weston --no-config --shell=fullscreen-shell.so --socket=wlhost-1
export WAYLAND_DISPLAY=wlhost-1
export QT_QPA_PLATFORM=wayland
papyros-shell

nothing appears on the screen, and nothing interesting appears in the logs.

However, if from an existing Wayland session, (with the standard desktop-shell.so)
I can do 
export QT_QPA_PLATFORM=wayland
papyros-shell
and get it in little window.

However I would perfer if I was able to use the fullscreen-shell with papyros, like I can with greenisland/hawaii-shell so I can call it from my waylandloginmanager as a selectible session, and use it as a guest session on weston's fullscreen-shell, instead of calling it as root, on eglfs.

I think weston itself also has a similar issue when running a standard desktop-shell based weston on a fuillscreen-shell, which I should probably report too, but greenisland works.

**Comment by iBeliever** [comment]
Good news, I'm working on a Green Island port of Papyros to evaluate switching to it completely.

Currently, on Arch Linux, I get a black screen when trying to run Hawaii or Green Island from the login manager, so nothing is ready to test, but I'll let you know when we have something that works.

**Comment by n3rdopolis** [comment]
cool. thanks!

**Comment by ricardomv** [comment]
you can also start the shell in fullscreen with the eglfs platform

**Comment by n3rdopolis** [comment]
ricardomv: I think that appears to require root permissions though, because eglfs doesn't support logind yet?

**Comment by iBeliever** [comment]
@n3rdopolis It can work without root permissions if you give your user access to the necessary device files. See [this post](http://blog.qt.io/blog/2015/01/20/qt-weekly-23-qt-5-5-enhancements-for-linux-graphics-and-input-stacks/), especially the Troubleshooting section.

**Comment by iBeliever** [comment]
I know it works because I've successfully used our current Papyros shell by logging in from GDM.

**Comment by ricardomv** [comment]
i think in virtual box you have to login as root to use eglfs

**Comment by n3rdopolis** [comment]
Yes. VirtualBox would require root because of the Framebuffer device, unless you grant the user permissions to /dev/fb0 manually
or add a 
SUBSYSTEM=="graphics", KERNEL=="fb*", TAG+="uaccess"
line to a /lib/udev/rules.d/ file... (although this causes issues with Weston https://bugs.freedesktop.org/show_bug.cgi?id=73782 I'm not sure how it would work with Qt's eglfs)

Thanks for your fast replies, I will probably wait for the greenisland port though, ...as I would have to readd slightly more insecure permissions to my waylandloginmanager for the input devices...

**Comment by iBelieve** [comment]
Papyros Shell is now based on GreenIsland, and can either use a Weston backend or render directly using eglfs.

**Comment by n3rdopolis** [comment]
How do I run it?

It only is is installing things to 
/opt/share/greenisland/io.papyros.shell

and nothing in
/opt/bin

I tried 
greenisland-launcher --fullscreen-shell -s io.papyros.shell

and I get a blank screen...
