### ISSUE TITLE
Yaourt compilation error: collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by FiveYellowMice** [papyros/papyros-shell#54]
Error message as shown below:

==> Continue building papyros-shell-git ? [Y/n]
==> -------------------------------------------
==> 
==> Building and installing package
==> Making package: papyros-shell-git b023cd5c-1 (Thu Mar 12 14:54:46 AEDT 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating papyros-shell git repo...
Fetching origin
==> Validating source files with sha256sums...
    papyros-shell ... Skipped
==> Extracting sources...
  -> Creating working copy of papyros-shell git repo...
Switched to a new branch 'makepkg'
==> Starting prepare()...
/tmp/yaourt-tmp-alex/aur-papyros-shell-git/src/papyros-shell /tmp/yaourt-tmp-alex/aur-papyros-shell-git/src
/tmp/yaourt-tmp-alex/aur-papyros-shell-git/src
/usr/lib/qt/bin/rcc -name papyros-shell ../papyros-shell/papyros-shell.qrc -o qrc_papyros-shell.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_COMPOSITOR_LIB -DQT_COMPOSITOR_WAYLAND_GL -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../papyros-shell -I. -I../papyros-shell/src -isystem /usr/include/qt -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtCompositor -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o qrc_papyros-shell.o qrc_papyros-shell.cpp
g++ -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro -o papyros-shell main.o qmlcompositor.o qrc_papyros-shell.o moc_qmlcompositor.o   -lQt5Compositor -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libQt5Compositor.so: undefined reference to `QDebug::putString(QChar const*, unsigned long)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libQt5Compositor.so: undefined reference to `QString::toUpper_helper(QString&)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libQt5Compositor.so: undefined reference to `QMetaType::registerNormalizedType(QByteArray const&, void (*)(void*), void* (*)(void*, void const*), int, QFlags<QMetaType::TypeFlag>, QMetaObject const*)'
collect2: error: ld returned 1 exit status
Makefile:226: recipe for target 'papyros-shell' failed
make: *** [papyros-shell] Error 1
==> ERROR: A failure occurred in prepare().
    Aborting...
==> ERROR: Makepkg was unable to build papyros-shell-git.
==> Restart building papyros-shell-git ? [y/N]

**Comment by ricardomv** [comment]
how did you install qtwayland? the error is in QtCompositor `Qt5Compositor.so: undefined reference to QDebug::putString`

**Comment by FiveYellowMice** [comment]
I install it from AUR via yaourt, followed all the dependencies.

**Comment by ricardomv** [comment]
Can you try to install qt5-wayland-git again?

**Comment by iBelieve** [comment]
Closing now as the package properly builds on our build server, so there shouldn't be any more problems.
