### ISSUE TITLE
Installation on Arch(problem w. qt5-base-git/qt5-wayland-dev-git)

### ISSUE THREAD

**Issue by aivel** [papyros/papyros-shell#57]
Hi! Get an error while trying to install Papyros-shell on Arch(from aur). The problem is with qt5-base-git package(when trying to install 0.0.3-1 version, http://joxi.ru/D2P4KNVhlYPY23) or with qt5-wayland-dev-git (806a7827-1 version, http://joxi.ru/l2Z1XznTOa1jmJ). How do I deal with it?
Thanks

**Comment by pspkzar** [comment]
I got the same issue as well. any way arround it?

**Comment by Manouchehri** [comment]
This isn't a Papyros problem. Issue should be closed.

If you actually read the comments on the AUR, you would see that both packages are unable to clone with git on Gitorious, so all you have to do is switch to HTTPS.

I'll fix both packages later this weekend and email the author with an updated PKGBUILD, but in the meantime all you have to do is change the one line.

**Comment by waldyrious** [comment]
> If you actually read the comments on the AUR

Link for convenience: https://aur.archlinux.org/packages/qt5-base-git#news

**Comment by Manouchehri** [comment]
I've adopted qt5-base-git and submitted a new PKGBUILD. I've emailed the maintainer of qt5-wayland-dev-git a new PKGBUILD as well, but as of now it has not been uploaded yet.

These messages should really be written on the AUR itself, not here. It's the wrong place. It's much easier to get in contact with package maintainers if you post where they expect you to.

**Comment by Manouchehri** [comment]
qt5-wayland-dev-git has been updated as well. There should be no more issues.

**Comment by aivel** [comment]
Thanks!
