### ISSUE TITLE
Qmake not working in Green Island branch

### ISSUE THREAD

**Issue by Collinthegeek** [papyros/papyros-shell#59]
I'm trying to compile the greenisland branch and have installed the dependencies with no problem at all. When I get to installing the shell itself Qmake asks me If I want to use project or makefile mode, I've tried both and neither one works. The error I get: 

$ qmake
Usage: qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project

Mode:
  -project       Put qmake into project file generation mode
                 In this mode qmake interprets files as files to
                 be built,
                 defaults to *; *; *; *.ts; *.xlf; *.qrc
                 Note: The created .pro file probably will 
                 need to be edited. For example add the QT variable to 
                 specify what modules are required.
  -makefile      Put qmake into makefile generation mode (default)
                 In this mode qmake interprets files as project files to
                 be processed, if skipped qmake will try to find a project
                 file in your current working directory

Warnings Options:
  -Wnone         Turn off all warnings; specific ones may be re-enabled by
                 later -W options
  -Wall          Turn on all warnings
  -Wparser       Turn on parser warnings
  -Wlogic        Turn on logic warnings (on by default)
  -Wdeprecated   Turn on deprecation warnings (on by default)

Options:
   * You can place any variable assignment in options and it will be     *
   * processed as if it was in [files]. These assignments will be parsed *
   * before [files].                                                     *
  -o file        Write output to file
  -d             Increase debug level
  -t templ       Overrides TEMPLATE as templ
  -tp prefix     Overrides TEMPLATE so that prefix is prefixed into the value
  -help          This help
  -v             Version information
  -after         All variable assignments after this will be
                 parsed after [files]
  -norecursive   Don't do a recursive search
  -recursive     Do a recursive search
  -set <prop> <value> Set persistent property
  -unset <prop>  Unset persistent property
  -query <prop>  Query persistent property. Show all if <prop> is empty.
  -cache file    Use file as cache           [makefile mode only]
  -spec spec     Use spec as QMAKESPEC       [makefile mode only]
  -nocache       Don't use a cache file      [makefile mode only]
  -nodepend      Don't generate dependencies [makefile mode only]
  -nomoc         Don't generate moc targets  [makefile mode only]
  -nopwd         Don't look for files in pwd [project mode only]
$

**Comment by iBeliever** [comment]
The GreenIsland port uses CMake instead of QMake. Compile the shell like this:

     $ mkdir build; cd build
     $ cmake ..
     $ make
     $ sudo make install

And run it using:

    $ greenisland -p io.papyros.shell

**Comment by Collinthegeek** [comment]
CMake Error at CMakeLists.txt:11 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 1.4.0) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!

**Comment by iBeliever** [comment]
@Collinthegeek Do you have [GreenIsland](https://github.com/greenisland/greenisland) installed? Make sure you have that and it's dependencies installed.

**Comment by Collinthegeek** [comment]
@iBeliever In AUR its showing up as greenisland but pacman isn't finding it,

**Comment by iBeliever** [comment]
@Collinthegeek `pacman` can't access the AUR. You need to manually install stuff from the AUR or use `yaourt`.

**Comment by iBelieve** [comment]
Closing as the `develop` branch now uses CMake and the QMake project files are gone. Please open a new issue if there are further problems with the CMake configuration.
