### ISSUE TITLE
Type NotificationsView unavailable...non-existent property "onNotificationRemoved"

### ISSUE THREAD

**Issue by flirtyheri** [papyros/papyros-shell#63]
Getting this error when launching papyros-shell on Arch-Linux with the most recent QT libs and Git Packages. 
qrc:/qml/Shell.qml:127:9: Type NotificationsView unavailable
qrc:/qml/notifications/NotificationsView.qml:86:9: Cannot assign to non-existent property "onNotificationRemoved"

**Comment by fedya** [comment]
same for me

**Comment by Psykopear** [comment]
Same here

**Comment by iBelieve** [comment]
The focus has now switched from the original shell to the Green Island-based one (now in the `develop` branch). This bug is fixed in the latest code in `develop`.
