### ISSUE TITLE
papyros develop branch doesn't install any executables

### ISSUE THREAD

**Issue by n3rdopolis** [papyros/papyros-shell#64]
I try 
greenisland-launcher --fullscreen-shell -s io.papyros.shell
but it doesn't appear to work?

In my checkinstalled deb it seems that only qml files are getting installed

Thanks

**Comment by n3rdopolis** [comment]
I think the README is out of date in the develop branch, as it still says to use qmake, and it seems there is no more papyros-shell binary that gets installed

**Comment by iBelieve** [comment]
The README is now updated to include up-to-date build instructions. Hope this helps!

**Comment by iBelieve** [comment]
Closing as the README is up-to-date.
