### ISSUE TITLE
Session management [$50 awarded]

### ISSUE THREAD

**Issue by iBelieve** [papyros/papyros-shell#68]
Lock, logout, shutdown, reboot, etc. in the system indicator.

This will require a C++ QML plugin to access the session API. This can possibly be forked from Hawaii desktop.

A power dialog will be implemented in #79.
##

**Comment by ctnlaring** [comment]
Does this enhancement include a login manager? ex: http://blog.lxde.org/wp-content/uploads/2010/01/lxdm-industrial-480x360.png

**Comment by iBelieve** [comment]
Fixed by 2575c9a0ba54d06f5a37558a5b4238b0ae934342.
