### ISSUE TITLE
Battery indicator [$15 awarded]

### ISSUE THREAD

**Issue by iBelieve** [papyros/papyros-shell#72]
Display primary battery information, as well as any additional batteries. The battery backend and indicator are already implemented, we just need a UI for the indicator popover.

Screen brightness will be implemented in #83.
##

**Comment by alexispurslane** [comment]
I was thinking about working on this, but I'm new to this project, and I'm not sure what you mean by a 'popover'.

**Comment by iBelieve** [comment]
@christopherdumas The popover is the view that slides up from the bottom bar when you tap on an indicator. This is controlled via the `view` property in the indicator classes (see https://github.com/papyros/papyros-shell/blob/develop/shell/indicators/BatteryIndicator.qml). We already have a battery backend, and a simple repeater for displaying batteries, so basically this just needs to a nice UI to be implemented for batteries, such as a progress bar for battery charge, etc.

Feel free to ping me in https://gitter.im/papyros/papyros if you want to work on this and have any questions.

**Comment by luxrck** [comment]
is it ok like this https://github.com/luxrck/papyros-shell/commit/f8fa81987bdfe4bb096a01a2a95a470f965d9c7e ?
