### ISSUE TITLE
Window manager branch - Cmake fails

### ISSUE THREAD

**Issue by ctnlaring** [papyros/papyros-shell#91]
I'm trying to install the window manager branch. When I run cmake it works for a bit then says:

CMake Error at CMakeLists.txt:15 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 1.4.0) with any of the following names:

```
ECMConfig.cmake
ecm-config.cmake
```

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/USER/papyros-window/papyros-shell/build/CMakeFiles/CMakeOutput.log".

**Comment by iBelieve** [comment]
The window manager branch is merged into the develop branch, so it's now outdated. However, you'll get the same error for the develop branch. If you're on Arch Linux, you can install the `extra-cmake-modules` (or an equivalent package for your distro).

**Comment by iBelieve** [comment]
Closing now as the window manager branch is outdated and the develop branch builds fine.
