### ISSUE TITLE
New app drawer broken

### ISSUE THREAD

**Issue by ctnlaring** [papyros/papyros-shell#95]
In the latest pull from git my app drawer is broken. I don't have the page layout and I can't start any apps. I do however have the new font and animations.

**Comment by iBelieve** [comment]
@Collinthegeek Is this still an issue?

**Comment by iBelieve** [comment]
@Collinthegeek I'm closing as the app drawer is working for me and others. If this is still an issue, please reopen with more details. Thanks!

**Comment by ctnlaring** [comment]
Yeah I fixed it. for some reason I have to delete it manually then rebuild
it every time it updates
